export const normalTheme = {
    background: "#222b00",
    headerColor: "#283618",
    arrowIconColor: "#dda15e",
    fontColor: "#ac9f0d",
    tabBarActiveTintColor: "#dda15e",
    tabBarInactiveTintColor: "#dda15e",
    bibLinkStyle: "#DDA15E",
    bibBackground: "#283618",
    grejLinkStyle: "#000",
    grejIconColor: "#dda15e",
    calculatorBackground: "#fefae0",
    redBlack: "black",
    blackRed: "red",
    calculatorButton: "#000",
    newBibBackground: "#fefae0",
    grejViAnbefaler: "#dda15e",
    afgrødeBeregnerButton: "#0000FF",
}

export const colorBlindTheme = {
    background: "#fff",
    headerColor: "#fff",
    arrowIconColor: "#000",
    fontColor: "#000",
    tabBarActiveTintColor: "#000",
    tabBarInactiveTintColor: "#000",
    bibLinkStyle: "#000",
    bibBackground: "#fff",
    grejLinkStyle: "#000",
    grejIconColor: "#fff",
    calculatorBackground: "#fff",
    redBlack: "red",
    blackRed: "black",
    calculatorButton: "#0000FF",
    newBibBackground: "#fff",
    grejViAnbefaler: "#000",
    afgrødeBeregnerButton: "#000",
}